Run cd simple_live_app

Running Gradle task 'assembleRelease'...                        
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/dart_simple_live/dart_simple_live/simple_live_app/android/app/build.gradle.kts' line: 44

* What went wrong:
null cannot be cast to non-null type kotlin.String

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 46s
Running Gradle task 'assembleRelease'...                          106.7s
Gradle task assembleRelease failed with exit code 1
Error: Process completed with exit code 1.
